### ISSUE TITLE
Build issues using publish.sh, and msbuild

### ISSUE THREAD

**Issue by jasonsturges** [CameronAavik/dotnetcore-graphics-example#2]
Hi, this is incredibly cool, but I'm having some issues on both Mac and PC.

### master branch

When running the publish.sh (or publish.cmd), both Mac and PC targets are giving errors:

> Microsoft (R) Build Engine version 15.1.548.43366
> Copyright (C) Microsoft Corporation. All rights reserved.
> 
> MSBUILD : error MSB1003: Specify a project or solution file. The current working directory does not contain a project or solution file.
> MSBUILD : error MSB1003: Specify a project or solution file. The current working directory does not contain a project or solution file.

Opening the project in VSCode, both Mac and PC give this error when restoring packages:

> error MSB4025: The project file could not be loaded. Data at the root level is invalid. Line 1, position 1.
> Done: 1.

### msbuild-loadlibrary-test branch

On the msbuild-loadlibrary-test branch, Mac and PC project doesn't compile, giving error:

> [/Users/jsturges/Projects/dotnetcore-graphics-example/dotnetcore-graphics-example.csproj]
/usr/local/share/dotnet/sdk/1.0.1/Sdks/Microsoft.NET.Sdk/build/Microsoft.NET.Sdk.DefaultItems.targets(165,5): error : Duplicate 'Compile' items were included. The .NET SDK includes 'Compile' items from your project directory by default. You can either remove these items from your project file, or set the 'EnableDefaultCompileItems' property to 'false' if you want to explicitly include them in your project file. For more information, see https://aka.ms/sdkimplicititems. The duplicate items were: 'Program.cs' [/Users/jsturges/Projects/dotnetcore-graphics-example/dotnetcore-graphics-example.csproj]
>     1 Warning(s)
>     1 Error(s)

If the Program.cs reference is removed the app launches with an empty window.  No triangle is rendered, which perhaps resembles Issue #1.

![image](https://cloud.githubusercontent.com/assets/1213591/25352432/9fea0bda-28f1-11e7-9aa0-929b49d0aa49.png)

Any tips or updates for this?

**Comment by CameronAavik** [comment]
I haven't actually looked at this project since I made the blog post, I did intend to work on the msbuild-loadlibrary-test branch but never got around to testing it on any other machines.

I'd say that the main branch is just outdated because of how the build system for .net core has changed so much, so I'd consider it broken for all intents and purposes and should be replaced by the msbuild branch when I have it working.

Regarding the second issue, I just cloned the msbuild-loadlibrary-test branch and was able to see the triangle though after fixing the csproj file. I'll just push a quick fix for the csproj file for the moment on that branch although since you already applied that alteration it probably won't fix the issue.

Could you try these:
1. Can you verify you have C:\Windows\System32\opengl32.dll on PC and /System/Library/Frameworks/OpenGL.framework/Versions/A/Libraries/libGL.dylib on Mac
2. Try downloading the latest glfw binaries from http://www.glfw.org/download.html and replacing them with the corresponding one in my project (make sure to rename them to the same name)
3. Remove the do-while loop in the code and replace it with the following which will mean you have to close the window by pressing enter in the command line:
```
DrawArrays(GL_TRIANGLES, 0, 3);
SwapBuffers(window);
Console.ReadLine();
```

**Comment by jasonsturges** [comment]
LibGL exists at that path, and I placed glfw v3.2.1 via brew into the project.

Thanks for the response - not sure why Mac has this issue, but I realize this repository accompanies a blog post from the past and is not an active endeavor.  Regardless, this is very cool, and demonstrated exactly what I wanted to know.  

No concerns - thanks for putting this together.
